export const projects = [
  {
    src: "/thirai.png",
    alt: "Thirai",
    title: "Thirai",
    description: "Your one stop for all your movie needs.",
    technology_used: ["react", "typescript", "nodejs", "mongodb", "tmdb"],
    live_link: "https://thirai.vercel.app/home",
    github_link: "https://github.com/loogark/thirai",
    translationKey: "thiraiDescription",
  },
  {
    src: "/blog.png",
    alt: "Techies Blog",
    title: "Techies Blog",
    description: "A Modern Blog with Headless CMS.",
    technology_used: ["Next.js", "TailwindCSS", "graphQl", "graphcms", "sass"],
    live_link: "https://techies-blog.vercel.app/",
    github_link: "https://github.com/loogark/techies_blog",
    translationKey: "blogDescription",
  },
  {
    src: "/tech.png",
    alt: "Techies",
    title: "Techies",
    description: "A social media app for like minded developers.",
    technology_used: ["React", "node.js", "express", "mongoAtlas", "Postman"],
    live_link: "https://techies-application.herokuapp.com/",
    github_link: "https://github.com/loogark/techies",
    translationKey: "techiesDescription",
  },
  {
    src: "/spotify.jpeg",
    alt: "spotify clone img",
    title: "React Spotify clone",
    description: "This is a Fullstack React Spotify Web application clone.",
    technology_used: [
      "React",
      "Bootstrap",
      "node.js",
      "axios",
      "spotify-web-api",
    ],
    github_link: "https://github.com/loogark/spotify-react",
    translationKey: "spotifyDescription",
  },
  {
    src: "/github.webp",
    alt: "Github clone img",
    title: "And many more...",
    description: "You can check out more of my projects on my github page.",
    technology_used: [],
    github_link: "https://github.com/loogark",
    translationKey: "gitHubDescription",
  },
];
